---
title: "FSB Student Success Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
#runtime: shiny
---
<style>
  body {
    background-color: #ffe3e3; 
  }
  
  .navbar {
    background-color: #C8102E; 
  }
  
  .header-button:active, .header-button:focus, .header-button:hover {
    background-color: red !important;
    color: white !important;
    border-color: red !important;
  }

</style>



```{r setup, include=FALSE,echo=FALSE}
knitr::opts_chunk$set(echo = TRUE,message=FALSE,warning=FALSE)

#package intialization
if(require(pacman)==FALSE) install.packages("pacman")
pacman::p_load(tidyverse, #for data manipulation
               plotly, #for interactive plots
               flexdashboard, #to make a dashboard
               fontawesome, #for icons
               DT #for better tables
               )
```

# Question Overview {data-orientation=columns}

## row {data-width=1000}

#### Question Overview: 

With this analysis, we will be answering the question surrounding FSB student's job placements post-graduation.
We will look at geographic trends to see where our students are going based on region, salary differentials by region,
what types of jobs students are getting by region, and finally, the top 3-5 job categories by city 
(Chicago, Cincinnati, Columbus, and Cleveland). These insights will aid FSB in being able to market to potential students and employers, guide students in their job search, and much more.

#### Insights and Links: 


# Survey Overview {data-orientation=columns}

Overview of survey responses
  
## row {data-width=300}

### Response Rate

### Usable Responses

### Students with Jobs




## row {data-height=600}

### Region of Job Placements

### Job Types
    



   

# Geography {data-orientation=columns}

## Column {data-width=600}

### Region Placement

### State Placement




## Column {data-width=400}

### Salary by Region

### Salary by City Adjusted for Cost of Living



# Cost by City {data-orientation=columns}

## Column {data-width=500}

### Chicago

### Columbus


## Column {data-width=500}

### Cincinnati

### Cleveland


# Cost by Region {data-orientation=columns}

## Column {data-width=500}

### Midwest

### North-East


## Column {data-width=500}

### West

### South

